export const RUNNER_CONFIG_FETCH_SUCCESS = '@RUNNER_CONFIG/FETCH_SUCCESS';
export const RUNNER_CONFIG_FETCH_START = '@RUNNER_CONFIG/FETCH_START';
export const RUNNER_CONFIG_FETCH_END = '@RUNNER_CONFIG/FETCH_END';
export const RUNNER_CONFIG_FETCH_ERROR = '@RUNNER_CONFIG/FETCH_ERROR';
